SELECT * FROM USER_LIB;
SELECT * FROM ALL_USERS;
SELECT * FROM USER_LIB;

SELECT M.*, B.*, R.* FROM MEMBER M, BOOK B, RENT R WHERE M.MEMBER_NO = R.MEMBER_NO AND B.BOOK_NO = R.BOOK_NO ORDER BY R.BOOK_NO