SELECT * FROM MEMBER;

SELECT MEMBER_NO , MEMBER_NAME , TEL , TOTAL_RENT FROM MEMBER;

INSERT INTO MEMBER values('M005', '박박박', '010-1111-1111', 0);

DELETE FROM MEMBER WHERE MEMBER_NO = 'M123';

UPDATE MEMBER SET MEMBER_NAME = '자자자', TEL = '010-5555-5555', TOTAL_RENT = 0 WHERE MEMBER_NO = 'M010';

/* 08월 20일 대현 끄적임 */
SELECT * FROM ALL_TABLES;

SELECT * FROM BOOK;
SELECT * FROM MEMBER;
SELECT * FROM RENT;
/*
ALTER TABLE BOOK MODIFY BOOK_NAME VARCHAR2(50);
ALTER TABLE BOOK MODIFY AUTHOR VARCHAR2(50);
ALTER TABLE BOOK MODIFY PUBLISHER VARCHAR2(50);
*/
INSERT INTO RENT VALUES('M004', '김바자', '010-4123-4123', 0);

/* Book 리스트 추가 */
SELECT BOOK_NO, BOOK_NAME, AUTHOR, PUBLISHER, PRICE, IS_RENT, TOTAL_COUNT FROM BOOK;

/* Book 저장 버튼 기능 */
INSERT INTO BOOK VALUES('B010', '책이름', '저자', '출판사', 25000, 1, 0);

SELECT * FROM BOOK;

/* Book 삭제 버튼 기능 */
DELETE FROM BOOK WHERE BOOK_NO = 'B010';

/* Book 수정 버튼 기능 */
UPDATE BOOK SET BOOK_NAME = '책이름', AUTHOR = '저자', PUBLISHER = '출판사', PRICE = 20000, IS_RENT = 1, TOTAL_COUNT = 0 WHERE BOOK_NO = 'B010';

SELECT * FROM RENT;

DELETE FROM RENT WHERE BOOK_NO = 'B001';
DELETE FROM RENT WHERE BOOK_NO = 'B002';
DELETE FROM RENT WHERE BOOK_NO = 'B003';
DELETE FROM RENT WHERE BOOK_NO = 'B004';

DROP TABLE RENT;
