SELECT * FROM MEMBER;

SELECT MEMBER_NO , MEMBER_NAME , TEL , TOTAL_RENT FROM MEMBER;

INSERT INTO MEMBER values('M005', '박박박', '010-1111-1111', 0);

DELETE FROM MEMBER WHERE MEMBER_NO = 'M123';

UPDATE MEMBER SET MEMBER_NAME = '자자자', TEL = '010-5555-5555', TOTAL_RENT = 0 WHERE MEMBER_NO = 'M010';

/* 08월 20일 대현 끄적임 */
SELECT * FROM ALL_TABLES;

SELECT * FROM BOOK;
SELECT * FROM MEMBER;
SELECT * FROM RENT;
/*
ALTER TABLE BOOK MODIFY BOOK_NAME VARCHAR2(50);
ALTER TABLE BOOK MODIFY AUTHOR VARCHAR2(50);
ALTER TABLE BOOK MODIFY PUBLISHER VARCHAR2(50);
*/
INSERT INTO RENT VALUES('M004', '김바자', '010-4123-4123', 0);


/*// 08월 20일 대현 끄적임 */

/*Book*/--
SELECT BOOK_NO, BOOK_NAME, AUTHOR, PUBLISHER, PRICE, IS_RENT, TOTAL_COUNT FROM BOOK;